tinyMCE.addI18n('fi.advanced_dlg',{
about_title:"About TinyMCE",
about_general:"About",
about_help:"Help",
about_license:"License",
about_plugins:"Plugins",
about_plugin:"Plugin",
about_author:"Author",
about_version:"Version",
about_loaded:"Loaded plugins",
anchor_title:"Insert/edit anchor",
anchor_name:"Anchor name",
code_title:"HTML Source Editor",
code_wordwrap:"Word wrap",
colorpicker_title:"Select a color",
colorpicker_picker_tab:"Picker",
colorpicker_picker_title:"Color picker",
colorpicker_palette_tab:"Palette",
colorpicker_palette_title:"Palette colors",
colorpicker_named_tab:"Named",
colorpicker_named_title:"Named colors",
colorpicker_color:"Color:",
colorpicker_name:"Name:",
charmap_title:"Select custom character",
image_title:"Insert/edit image",
image_src:"Kuvan osoite",
image_alt:"Kuvan kuvaus",
image_list:"Kuvalista",
image_border:"Reunus",
image_dimensions:"Mitat",
image_vspace:"Pystysuuntainen tila",
image_hspace:"Vaakasuuntainen tila",
image_align:"Tasaus",
image_align_baseline:"Tekstin tasossa",
image_align_top:"Yl\u00F6s",
image_align_middle:"Keskelle",
image_align_bottom:"Alas",
image_align_texttop:"Tekstin yl\u00E4osaan",
image_align_textbottom:"Tekstin alaosaan",
image_align_left:"Vasemmalle",
image_align_right:"Oikealle",
link_title:"Lis\u00E4\u00E4/muuta linkki",
link_url:"Linkin osoite",
link_target:"Kohde",
link_target_same:"Avaa linkki samassa ikkunassa",
link_target_blank:"Avaa linkki uuteen ikkunaan",
link_titlefield:"Otsikko",
link_is_email:"Antamasi osoite n\u00E4ytt\u00E4\u00E4 olevan s\u00E4\u00E4hk\u00F6postiosoite. Haluatko lis\u00E4t\u00E4 siihen mailto:-etuliitteen?",
link_is_external:"Antamasi osoite n\u00E4ytt\u00E4\u00E4 johtavan ulkopuoliselle sivustolle. Haluatko lis\u00E4t\u00E4 linkin eteen http://-etuliitteen? (suositus)",
link_list:"Linkkilista"
});