var tocTab = new Array();
	tocTab[0] = new Array ("0", "", "");
	tocTab[1] = new Array ("1", "Institucion", "../admin/institucion/listarInstituciones.php3");
	tocTab[2] = new Array ("1.1", "Año academico", "texto.php3?idMenu=1");
	tocTab[3] = new Array ("1.1.2", "Cursos", "texto.php3?idMenu=2");
	tocTab[4] = new Array ("1.1.2.1", "Alumnos", "texto.php3?idMenu=2");
	tocTab[5] = new Array ("1.1.3", "Actas", "texto.php3?idMenu=3");
	tocTab[6] = new Array ("1.1.4", "Reportes", "texto.php3?idMenu=4");
	tocTab[7] = new Array ("1.1.5", "Agenda Web", "texto.php3?idMenu=5");
	tocTab[8] = new Array ("1.1.6", "Centro de alumnos", "texto.php3?idMenu=6");
	tocTab[9] = new Array ("1.1.6.1", "Actividades", "texto.php3?idMenu=7");
	tocTab[10] = new Array ("1.1.6.2", "Diario electronico", "texto.php3?idMenu=8");
	tocTab[11] = new Array ("1.1.6.3", "Agenda Web", "texto.php3?idMenu=9");
	tocTab[12] = new Array ("1.1.7", "Centro de padres", "texto.php3?idMenu=10");
	tocTab[13] = new Array ("1.1.7.1", "Actividades", "texto.php3?idMenu=11");
	tocTab[14] = new Array ("1.1.7.2", "Diario electronico", "texto.php3?idMenu=12");
	tocTab[15] = new Array ("1.1.7.3", "Agenda Web", "texto.php3?idMenu=13");
	tocTab[16] = new Array ("1.1.8", "Cuenta corriente alumnos", "texto.php3?idMenu=14");
	tocTab[17] = new Array ("1.1.9", "Diario electronico", "texto.php3?idMenu=15");
	tocTab[18] = new Array ("1.1.10", "Periodos", "texto.php3?idMenu=16");
	tocTab[19] = new Array ("1.2", "Biblioteca", "texto.php3?idMenu=17");
	tocTab[20] = new Array ("1.3", "Empleados", "texto.php3?idMenu=18");
	tocTab[21] = new Array ("1.3.1", "Docentes", "texto.php3?idMenu=19");
	tocTab[22] = new Array ("1.4", "Estancias", "texto.php3?idMenu=20");
	tocTab[23] = new Array ("1.5", "Reportes", "texto.php3?idMenu=21");
	tocTab[24] = new Array ("1.5.1", "Alumno", "texto.php3?idMenu=21");
	tocTab[25] = new Array ("1.5.1.1", "Informe de Notas", "texto.php3?idMenu=21");
	tocTab[26] = new Array ("1.5.1.2", "Asistencia y atrasos", "texto.php3?idMenu=21");
	tocTab[27] = new Array ("1.5.1.3", "Observaciones", "texto.php3?idMenu=21");
	tocTab[28] = new Array ("1.5.2", "Curso", "texto.php3?idMenu=21");
	tocTab[29] = new Array ("1.5.2.1", "Listado Cursos", "texto.php3?idMenu=21");
	tocTab[30] = new Array ("1.5.2.2", "Alumnos", "texto.php3?idMenu=21");
	tocTab[31] = new Array ("1.5.2.3", "Asignaturas", "texto.php3?idMenu=21");
	tocTab[32] = new Array ("1.5.2.4", "Pago Mensualidades", "texto.php3?idMenu=21");
	tocTab[33] = new Array ("1.5.2.5", "Ficha Medica", "texto.php3?idMenu=21");
	tocTab[34] = new Array ("1.5.2.6", "Historial Enfermeria", "texto.php3?idMenu=21");
var nCols = 6;